coverage:
  precision: 2
  range: 70...100
  round: down
  status:
    project: true
    patch: true
    changes: false

comment:
  layout: 'header, diff, tree'
  behavior: default
  require_changes: true

ignore:
  - './coverage/tmp/'
