coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    # Learn more at http://docs.codecov.io/docs/codecov-yaml
    project: true
    patch: true
    changes: false

comment:
  layout: "header, diff, tree"
  behavior: default  # update if exists else create new

ignore:
  - "./coverage/tmp/"

