comment:
  behavior: default
  layout: 'header, diff, tree'
  require_changes: true

coverage:
  precision: 2
  range: 70...100
  round: down
  status:
    changes: false
    patch: true
    project: true

ignore:
  - './coverage/tmp/'
