version: 2

updates:
  - cooldown:
      default-days: 7
      include:
        - '*'
    directory: '/'
    groups:
      actions:
        update-types:
          - 'minor'
          - 'patch'
    labels: []
    open-pull-requests-limit: 5
    package-ecosystem: 'github-actions'
    schedule:
      day: monday
      interval: weekly
      time: '07:00'
      timezone: Etc/UTC
