#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

pnpm exec syncpack fix-mismatches \
  --types dev,prod,peer,engines || exit 1

pnpm exec syncpack set-semver-ranges \
  --types dev,prod,peer,engines || exit 1

pnpm exec syncpack format || exit 1

pnpm install
git add package.json pnpm-lock.yaml

pnpm exec ls-lint || exit 1
pnpm exec lint-staged || exit 1
pnpm run typecheck || exit 1
pnpm run test || exit 1
