name: release-github-pages

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    permissions:
      checks: read
      contents: read
      pull-requests: read
      statuses: read
    uses: escapace/workflows/.github/workflows/context.yaml@trunk

  continuous-integration:
    needs:
      - context
    permissions:
      contents: read
      packages: read
    uses: escapace/workflows/.github/workflows/ci-typescript.yaml@trunk
    with:
      enable-artifact-upload: false
      enable-codecov: false
      enable-github-pages: ${{ fromJSON(needs.context.outputs.github-pages) }}
      github-pages-path: ${{ needs.context.outputs.github-pages-path }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      ref: ${{ needs.context.outputs.ref }}
      version: ${{ needs.context.outputs.version }}

  release-github-pages:
    if: needs.context.outputs.github-pages
    needs:
      - context
      - continuous-integration
    permissions:
      contents: read
      id-token: write
      pages: write
    uses: escapace/workflows/.github/workflows/release-github-pages.yaml@trunk
